/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#3f2c23",
        "surface-bright": "#42372f",
        "on-primary-container": "#67490b",
        "inverse-primary": "#79591b",
        "on-secondary-container": "#cbafa2",
        "surface-container-lowest": "#140d06",
        "secondary-fixed": "#fbdcce",
        "error-container": "#93000a",
        "on-primary-fixed": "#271900",
        "tertiary-fixed": "#baf464",
        "primary": "#ffd796",
        "surface-variant": "#3d332b",
        "primary-container": "#e5ba73",
        "primary-active": "#166534",
        "primary-active-light": "#1a7a3d",
        "on-error": "#690005",
        "on-surface": "#f1dfd3",
        "on-background": "#f1dfd3",
        "outline-variant": "#4e4539",
        "surface-dim": "#1a120b",
        "surface-container-low": "#221a13",
        "inverse-on-surface": "#382f26",
        "on-secondary-fixed": "#281810",
        "on-secondary-fixed-variant": "#574238",
        "tertiary": "#95CD41",
        "on-primary": "#422c00",
        "on-tertiary-container": "#385700",
        "on-tertiary-fixed": "#111f00",
        "background": "#1a120b",
        "primary-fixed": "#ffdeab",
        "on-error-container": "#ffdad6",
        "outline": "#9a8f80",
        "secondary-fixed-dim": "#dec1b3",
        "surface-container-high": "#322820",
        "tertiary-container": "#99d145",
        "secondary-container": "#574238",
        "on-primary-fixed-variant": "#5f4103",
        "primary-fixed-dim": "#ebc078",
        "tertiary-fixed-dim": "#9fd74a",
        "surface-tint": "#ebc078",
        "surface-container-highest": "#3d332b",
        "surface": "#1a120b",
        "inverse-surface": "#f1dfd3",
        "surface-container": "#271e16",
        "secondary": "#dec1b3",
        "error": "#ffb4ab",
        "on-surface-variant": "#d2c5b4",
        "on-tertiary-fixed-variant": "#324f00",
        "on-tertiary": "#213600"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
        inter: ["Inter", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      }
    },
  },
  plugins: [],
}
